schema = 3

[mod]
  [mod."github.com/a-h/templ"]
    version = "v0.2.707"
    hash = "sha256-UoM2qj8E7C4NBAMhS/2jrOw0Dj/gnsyZRL4NpRCWaMo="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.0.12"
    hash = "sha256-PhCb3wVSzuIXxZxM7aB3MdMLK3nnvUMhaMXk+p+H6Ec="
